import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar, Footer } from '@/components'
import { ClerkProvider } from '@clerk/nextjs'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
    <html lang="en">
      <head>
        
      </head>
      
      <body className={inter.className}>
        <Navbar />
        <main className='container'>
          <div className="flex items-start justify-center min-h-screen">
          <div className='mt-20'>
          {children}
          </div>
          </div>
        

        </main>
       <Footer />
        </body>
    </html>
    </ClerkProvider>
  )
}
